# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Automation Suite CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
 
  build:    
    name: Build and Test automation Framework
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env: # Or as an environment variable
        TEST_ENVIRONMENT: "prod"
        API_USER: ${{ secrets.API_USER }}
        API_PASSWORD: ${{ secrets.API_PASSWORD }}
        UI_USER: ${{ secrets.UI_USER }}
        UI_PASSWORD: ${{ secrets.UI_PASSWORD }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run cypress:run